# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-11-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0002_auto_20211107_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dumb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stupid',
            field=models.IntegerField(default=0),
        ),
    ]
